language: ruby
rvm:
  - 2.3.0
services:
  - postgresql
  - elasticsearch
before_script:
  - ls -la /usr/share
  - psql -c 'create database app_test;' -U postgres
  - sleep 10 # To make sure Elasticsearch instance is ready
test:
  adapter: postgresql
  database: travis_ci_test